### ISSUE TITLE
SGA V10.0 / Age of Empires 4 / Company of Heroes 3 Support

### ISSUE THREAD

**Issue by ModernMAK** [MAK-Relic-Tool/Issue-Tracker#5]

**Comment by ModernMAK** [comment]
See #45

Probably the least egregious, there are plenty of tools that handle AoE4, and CoH3 probably can use the same tools

**Comment by odragora** [comment]
> Probably the least egregious, there are plenty of tools that handle AoE4

Could you please tell what tools that handle AoE 4 you are talking about?

I'm trying to find a solution to decode .rec files that are used for match replays, with the goal of creating an app that would help the players analyse their matches and improve at the game.
Haven't been able to find anything close to what you are doing.

**Comment by ModernMAK** [comment]
# Other Tools (probably not what you want)
This thread was specifically talking about tools handling relic SGA files

The big tool i found for that was **[AOEMods.Essence](https://github.com/aoemods/AOEMods.Essence)**

It might handle your use-case, but I haven't peeked at it since I closed this. It's also C#, not python, if that's a deal breaker.

But that's probably not what your looking for.

# Regarding .rec files
If you could take a peek in a text/hex editor, do .rec files begin with `Relic Chunky` if so, then it's a chunky file, and I might be able to help you dump the data tree, but it'd be up to you to parse it into anything meaningful

Otherwise, its not an archive format, I won't be able to help, sorry.

**Comment by odragora** [comment]
Thank you for a quick and detailed response!

> If you could take a peek in a text/hex editor, do .rec files begin with Relic Chunky if so, then it's a chunky file, and I might be able to help you dump the data tree

Yes, .rec files have multiple entries of `Relic Chunky` at the beginning.

![Image](https://github.com/user-attachments/assets/37aa8a1b-997c-431e-9316-9830064b0464)

**Comment by ModernMAK** [comment]
Huh, neat
So .rec files are *another* archive format, containing several chunky files

That's more work than I was hoping for, modifying my old chunky extractor for V4 is as easy as determining the chunky header size and ignoring some of the non critical bits

I could probably still get you a lite script that takes a python file handle and an offset, so you could skim the file for the Relic Chunky Headers, but you'd lose the tree or any other critical metadata that the .rec specification provides

In any case, SGA-V2's been waiting for a 2.0 release for 2 years, and currently has most of my attention, I could get a crude Chunky V4 extractor script to you sometime this or next week.

I AM interested though; archive formats are a lot easier to fiddle with because I don't have to guess what data is supposed to be (looking at you .whm files).
So I'm gonna make a separate issue for that, but SGA-V2 is coming first.

**Comment by odragora** [comment]
Thank you so much for your help!

I definitely look forward to this, if you'll have time for it.

**Comment by petrvecera** [comment]
@odragora for replay parsing check https://github.com/ryantaylor/vault
